feat: fare media vote passes update
MobilityData/gtfs.org pull request #115
Opened 2023-03-14 17:09 UTC by emmambd

Announcing that the fare media vote has passed on gtfs.org.

2023-03-14 23:45 UTC, isabelle-dr approved these changes
LGTM

2023-03-16 19:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MobilityData/gtfs.org?pullRequest=115) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MobilityData/gtfs.org?pullRequest=115) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: emmambd<br/>:white_check_mark: isabelle-dr<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MobilityData/gtfs.org?pullRequest=115) it.</sub>

2023-03-20 18:13 UTC, josee-sabourin requested changes

2023-03-20 18:13 UTC, josee-sabourin commented on docs/extensions/fares-v2.ja.md
generally seems to be markdown errors in the history section, ex: year only in bold and not month

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.de.md
> +|  `fare_media_name` | Text | Fakultativ | Name des Tarifmediums.<br/><br/>Für Tarifmedien, bei denen es sich um Transitkarten`(fare_media_type =2`) oder mobile Apps`(fare_media_type =4`) handelt, so
opening brackets formatted as code on both occasions

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.de.md
> +|  `fare_media_type` | Enum | **Erforderlich** | Der Typ der Tarifmedien. Gültige Optionen sind:<br/><br/>0 - Keine. Wird verwendet, wenn beim Kauf oder bei der Validierung eines Fahrpreisprodukts ke
enums 
(numbers) not formatted as code

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.es.md
> +| [fare_media.txt](#fare_mediatxt) | Opcional | Describir los medios tarifarios que pueden emplearse para utilizar productos tarifarios.<br/><br/>El archivo [fare_media](#fare_mediatxt).txt describe
First sentence:
- .txt not included in hyperlink in first  fare_media.txt
- extra xt after fare_attributes.txt hyperlink
- extra fare_rules before and extra txt after fare_rules.txt

Second sentence:
- extra xt after fare_attributes.txt
- extra fare_rules before and extra txt after fare_rules.txt

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.es.md
> +|  `fare_media_type` | Enum | **Exigida** | El tipo de medio de tarifa. Las opciones válidas son:<br/><br/>0 - Ninguno. Se utiliza cuando no hay ningún medio de pago implicado en la compra o validaci
enum numbers not formatted as code

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.fr.md
> +| [fare_media.txt](#fare_mediatxt) | Optionnelle | Décrire les supports tarifaires qui peuvent être utilisés pour utiliser les produits tarifaires.<br/><br/>Le fichier [fare_media.txt](#fare_mediatxt
extra xt after fare_attributes.txt in first sentence

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.id.md
> +| [fare_media.txt](#fare_mediatxt) | Opsional | Mendeskripsikan media tarif yang dapat digunakan untuk menggunakan produk tarif.<br/><br/>File [fare_media.txt](#fare_mediatxt) menjelaskan konsep yang
missing hyperlinks for fare_attributes.txt and fare_rules.txt in both sentences

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.id.md
> +| `fare_media_id`   |  Identitas unik | ** Yg dibutuhkan** |  Mengidentifikasi media tarif.
** Yg dibutuhkan** not appearing in bold

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.id.md
> +| `fare_media_type` |  enum           | ** Yg dibutuhkan** |  Jenis tarif media. Opsi yang valid adalah:<br/><br/>`0` - Tidak ada. Digunakan saat tidak ada media tarif yang terlibat dalam pembelian a
** Yg dibutuhkan** not appearing in bold

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.id.md
> +| `fare_product_id`   |  Identitas        | ** Yg dibutuhkan** | Mengidentifikasi produk tarif.
** Yg dibutuhkan** not appearing in bold

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.id.md
> +| `amount`            |  Jumlah mata uang | ** Yg dibutuhkan** | Biaya produk tarif. Mungkin negatif untuk menunjukkan diskon transfer. Mungkin nol untuk mewakili produk tarif yang gratis.
** Yg dibutuhkan** not appearing in bold

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.id.md
> +| `currency`          |  Kode mata uang   | ** Yg dibutuhkan** | Mata uang biaya produk tarif.
** Yg dibutuhkan** not appearing in bold

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.ko.md
> +| `fare_media_id`   |  고유 ID | ** 필수의** |  운임 매체를 식별합니다.
** 필수의** not appearing in bold

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.ko.md
> +| `fare_media_type` |  열거    | ** 필수의** |  요금 매체의 유형입니다. 유효한 옵션은 다음과 같습니다.<br/><br/>`0` - 없음. 실물 티켓이 제공되지 않은 상태에서 기사나 차장에게 현금을 지불하는 것과 같이 운임 제품 구매 또는 확인과 관련된 운임 매체가 없을 때 사용됩니다.<br/>`2` - 티켓, 패스 또는 금전
** 필수의** not appearing in bold

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.ru.md
> +Первичный ключ (`fare_product_id`)
missing fare_media_id

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.zh_TW.md
> +| [fare_media.txt](#fare_mediatxt) | 可选的 | 描述可用於使用票價產品的票價媒體。<br/><br/>文件[fare_media.txt](#fare_mediatxt)描述了未在fare_attributes.txt和fare_rules.txt .因此， [fare_media.txt](#fare_mediatxt)的使用與文件完全分開[fare_at
missing hyperlinks for fare_attributes.txt and fare_rules.txt in first sentence

2023-03-20 18:13 UTC, josee-sabourin commented on docs/schedule/reference.zh_TW.md
> +| `fare_media_id` | 国外身份证参考 `fare_media.fare_media_id` |  標識可用於在旅行期間使用票價產品的票價媒體。當`fare_media_id`是空的，認為票價媒體是未知.|
error with the columns here

2023-03-21 11:50 UTC, josee-sabourin approved these changes

2023-03-21 12:57 UTC, merged