Flex Extension Page
MobilityData/gtfs.org pull request #150
Opened 2023-06-08 21:36 UTC by eliasmbd

Well here we are. I think I finally made my first PR! 

I took inspiration from the Fares v2 page to create the Flex page on GTFS.org. 

I included some basic info about the spec proposal, airtables and some history. 

Let me know what you think and if it makes sense to you.

2023-06-08 21:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MobilityData/gtfs.org?pullRequest=150) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MobilityData/gtfs.org?pullRequest=150) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MobilityData/gtfs.org?pullRequest=150) it.</sub>

2023-06-18 21:24 UTC, emmambd requested changes
Hi @eliasmbd! A couple small changes here to fix/take into consideration, and then I'll merge the PR. Should be ready to go by EOD Monday assuming you make the modifications.

2023-06-18 21:24 UTC, emmambd commented on docs/extensions/flex.md
> +<img src="../assets/flex-userjourney-resize.jpg" alt="GTFS-Flex User Journey">
fix: Path is broken. Should be: 

> src="../../assets/flex-userjourney-resize.jpg"

2023-06-18 21:24 UTC, emmambd commented on docs/extensions/flex.md
> +## WIP: Base Implementation
fix: Worth removing WIP and changing all "base implementation" references to "Service Discovery".

2023-06-18 21:24 UTC, emmambd commented on docs/extensions/flex.md
> +We have opened an issue to cover the base implementation of GTFS-Flex. Using this incremental approach should allow us to better establish a strong base for consensus.
fix: "We" isn't clear to use on gtfs.org, since it's a community-wise resource. I'd reference MobilityData explicitly here.

2023-06-18 21:24 UTC, emmambd commented on docs/extensions/flex.md
> +Contact us to add your GTFS-Flex implementation to this page
suggestion: This button should go to an email address rather than Slack, since the point of contact isn't clear if they're just directed to Slack.

2023-06-18 21:24 UTC, emmambd commented on docs/extensions/flex.md
> +### Future
suggestion: Looks like there's no current Future info - I'd suggest removing it from the page until there's actual submissions.

2023-06-18 21:24 UTC, emmambd commented on docs/extensions/flex.md
> +- **2016**: <a href="https://github.com/MobilityData/gtfs-flex/tree/master" target="_blank">GTFS-Flex GitHub discussions begin</a>
suggestion: These two first hyperlinks go to the same place. I'd remove the hyperlink if there's no direct reference here to when the discussions began.

2023-06-18 21:24 UTC, emmambd commented on docs/extensions/flex.md
> +🤔 As many of you know, services like dial-a-ride are often brushed over by riders, who sometimes have no clue they even exist. This lack of accessibility is an issue for producers, consumers, and rid
nit: Since dial-a-ride is a smaller use case example, are there others worth referencing here instead or in addition?

2023-06-19 19:05 UTC, eliasmbd reviewed
Made the changes @emmambd commented on.

2023-06-19 19:05 UTC, eliasmbd commented on docs/extensions/flex.md
> +🤔 As many of you know, services like dial-a-ride are often brushed over by riders, who sometimes have no clue they even exist. This lack of accessibility is an issue for producers, consumers, and rid
Will add glossary at bottom of page

2023-06-19 19:05 UTC, eliasmbd commented on docs/extensions/flex.md
> +### Future
Resolved it by adding a description and invite to add future intentions

2023-06-19 20:52 UTC, eliasmbd reviewed
Sounds good to me

2023-06-19 21:00 UTC, emmambd approved these changes

2023-06-19 21:01 UTC, merged