docs: fixes for japanese translations
MobilityData/gtfs.org pull request #211
Opened 2023-10-25 12:49 UTC by emmambd

This PR 

- Applies suggested translations fixes for Japanese content
- Updates homepage and Training content on the GTFS Schedule section to match with English version

2023-10-26 20:28 UTC, tzujenchanmbd requested changes
[ja_realtime] 

- Missing 1 section
- revise 1 link

2023-10-26 20:28 UTC, tzujenchanmbd commented on docs/realtime/index.ja.md
Line 47 - 53 "データ形式" need update

2023-10-26 20:28 UTC, tzujenchanmbd commented on docs/realtime/changes/index.ja.md
> +最近追加された提案は、[公式のGTFS Realtime 仕様](../reference)として機能するようになりました。詳しくは[リビジョンヒストリーを](../process#revision-history)ご覧ください。
exclude "を" from link

2023-10-27 14:00 UTC, tzujenchanmbd commented on docs/realtime/index.ja.md
Commit pushed https://github.com/MobilityData/gtfs.org/pull/211/commits/17a462d25d141bc12108e24f84569e395442d143

2023-10-27 14:00 UTC, tzujenchanmbd commented on docs/realtime/changes/index.ja.md
> +最近追加された提案は、[公式のGTFS Realtime 仕様](../reference)として機能するようになりました。詳しくは[リビジョンヒストリーを](../process#revision-history)ご覧ください。
Commit pushed https://github.com/MobilityData/gtfs.org/pull/211/commits/ac6953945b72031d48f788eb58503ca7f8ab9b02

2023-10-27 15:43 UTC, tzujenchanmbd approved these changes

2023-10-27 20:44 UTC, isabelle-dr commented
@bdferris-v2 this PR contains the fixes to the Japanese translations if you'd like to review them.

2023-10-30 16:50 UTC, bdferris-v2 commented
Thanks @isabelle-dr .  I've passed this onto my colleagues and they might make some comments on the PR directly.  I'll let you know when we are done reviewing.

2023-11-16 12:25 UTC, fredericsimard reviewed
@tzujenchanmbd About this [commit](https://github.com/MobilityData/gtfs.org/pull/211/commits/deb29cb57857a4c5734e9a368208273ff4c1e465), the `"!!! note """` should not be removed, this is MKDocs code to put the paragraph that follows inside a notes box like in all other languages, like the blue box on this page : https://gtfs.org/realtime/changes/

2023-11-16 14:40 UTC, tzujenchanmbd commented
@fredericsimard Have added this back, thanks!

2023-11-16 15:21 UTC, merged