Update tables for the remaining components after confirming format
MobilityData/gtfs.org pull request #368
Opened 2024-02-22 21:15 UTC by isabelle-dr

This PR updates the tables that have the list of files and fields included on the individual component pages

2024-02-23 14:48 UTC, tzujenchanmbd requested changes
lgtm except 2 tiny editorial changes

2024-02-23 14:48 UTC, tzujenchanmbd commented on docs/documentation/schedule/components/base.md
> +|[agency.txt](/schedule/reference/#agencytxt)|`agency_name`, `agency_url`, `agency_timezone`, `agency_lang`, `agency_phone`, `agency_fare_url`, `agency_email |
```suggestion
|[agency.txt](/schedule/reference/#agencytxt)|`agency_name`, `agency_url`, `agency_timezone`, `agency_lang`, `agency_phone`, `agency_fare_url`, `agency_email` |
```

2024-02-23 14:48 UTC, tzujenchanmbd commented on docs/documentation/schedule/components/base.md
> +|[stop_times.txt](/schedule/reference/#stop_timestxt)|`trip_id`, `arrival_time`, `departure_time`, `stop_id`, `stop_sequence`, `pickup_type`, `drop_off_type`, `` |
```suggestion
|[stop_times.txt](/schedule/reference/#stop_timestxt)|`trip_id`, `arrival_time`, `departure_time`, `stop_id`, `stop_sequence`, `pickup_type`, `drop_off_type`, `timepoint` |
```

2024-02-26 18:28 UTC, isabelle-dr commented
Fixed :) 
PTAL

2024-02-26 19:07 UTC, tzujenchanmbd approved these changes

2024-02-26 19:08 UTC, merged