Add data samples and requirements to Base features
MobilityData/gtfs.org pull request #416
Opened 2024-04-12 19:28 UTC by Sergiodero

Changes to base features include:

- Adds data samples for each feature
- Adds requirements for each feature
- Fixes link to reference.md
- Adds timepoint as a field associated with stop_times

2024-04-24 13:40 UTC, isabelle-dr requested changes
Same meta comments than in the other PRs

- Line break after the ??? note "Sample Data"
- Replace "the following table" with "the following sample"
- Pre-requirements: maybe "all other Base features"?

2024-04-24 13:40 UTC, isabelle-dr commented on docs/getting_started/features/base.md
> +    The following table shows basic agency information provided for this file.
This is repetitive on the feature description above. I think we can remove it, given that the sample is self-explanatory.

2024-04-24 13:40 UTC, isabelle-dr commented on docs/getting_started/features/base.md
> +    The following table defines a stop providing basic information elements to identify it and locate the stop.
This is repetitive on the feature description above. I think we can remove it, given that the sample is self-explanatory.

2024-04-24 19:29 UTC, Sergiodero commented
The meta comments have been solved and the descriptions for the agency and stops data samples has been removed. do you mind taking a final look before merging @isabelle-dr? thanks!

2024-04-25 09:32 UTC, isabelle-dr commented on docs/getting_started/features/base.md
> +|[stop_times.txt](/documentation/schedule/reference/#stop_timestxt)|`trip_id`, `arrival_time`, `departure_time`, `stop_id`, `stop_sequence`, `pickup_type`, `drop_off_type`, `time_point` |
it's _timepoint_ not _time_point_

2024-04-25 09:32 UTC, isabelle-dr approved these changes
LGTM!

2024-04-25 14:12 UTC, Sergiodero commented on docs/getting_started/features/base.md
> +|[stop_times.txt](/documentation/schedule/reference/#stop_timestxt)|`trip_id`, `arrival_time`, `departure_time`, `stop_id`, `stop_sequence`, `pickup_type`, `drop_off_type`, `time_point` |
Fixed!

2024-04-25 14:13 UTC, merged