Add data samples to Transfers feature
MobilityData/gtfs.org pull request #425
Opened 2024-04-15 20:38 UTC by Sergiodero

Changes include:

- Adds data samples
- Adds requirements 
- Fixes link to reference.md

2024-04-24 13:36 UTC, isabelle-dr requested changes
Same meta comments than in the other PRs

- Line break after the ??? note "Sample Data"
- Replace "the following table" with "the following sample"
- Pre-requirements without the "implement" and remove "s"

2024-04-24 13:36 UTC, isabelle-dr commented on docs/getting_started/features/transfers.md
>  Transfers provide details about transitions between different travel segments (or legs), enabling trip planners to determine the feasibility of journeys that include transfers.
I think this section in the GTFS Books is a nice addition to the feature description (I have modified it a bit).

> Specifying transfers doesn't imply passengers can't transfer elsewhere. It just shows whether certain transfers are not possible or require a minimum time to transfer.

2024-04-24 21:28 UTC, Sergiodero commented
Comments are now addressed, the suggested text was added to the description.

2024-04-25 09:05 UTC, isabelle-dr approved these changes
LGTM!

2024-04-25 19:44 UTC, merged